name: Corrine
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7793
title: Corrine Kenner
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#040404'
    - '#163762'
    - '#9a6aa6'
    - '#c7c1c3'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
