name: Corrine
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7793
title: Corrine Kenner
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d4af37'
    - '#000000'
    - '#ff8000'
    - '#808000'
    - '#aaaa00'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
