name: Corrine
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7793
title: Corrine Kenner
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d4af37'
    - '#000000'
    - '#ff8000'
    - '#808000'
    - '#aaaa00'
  brandStrength: 0.8799190944992006
  lightness: 0.8415894098579884
  saturation: 0.4961027125827968
  rhythmicContrast: 0.3557552595157176
purpose: []
