name: Corrine
favicon: null
layout_spectrum: 0.15625
typography_spectrum: 0.32227
title: C o R r I n I n G  o U t  O f  C o N t R o L
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#040404'
    - '#163762'
    - '#9a6aa6'
    - '#c7c1c3'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
